[package]
name = "kv-raft-example"
version.workspace = true
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1.89"
kv = { path = "../kv" }
raft-rs = { path = "../raft-rs" }
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.27.0"
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = ["full"] }
